### ISSUE TITLE
DOESN'T WORK!

### ISSUE THREAD

**Issue by wasgood566** [HarshalCODE/Bypass-Hcaptcha-On-Any-Site#2]
DOESN'T WORK..

**Comment by HarshalCODE** [comment]
It Work Perfectly Fine
Tell me what Error u got 
Pls specify Screenshot

**Comment by wasgood566** [comment]
> It Work Perfectly Fine Tell me what Error u got Pls specify Screenshot

https://i.imgur.com/YPCtkk2.png

**Comment by wasgood566** [comment]
Also, a friend of mine tried it and it didn't work! it doesn't solve the captcha at all.

https://i.imgur.com/G4YflD1.png

**Comment by HarshalCODE** [comment]
Bro in image u are trying with an Google captcha 
See discription of this report it solve hcaptcha

**Comment by wasgood566** [comment]
> Bro in image u are trying with an Google captcha See discription of this repository it solve hcaptcha
can u send a picture of the HCaptcha?

**Comment by wasgood566** [comment]
> Bro in image u are trying with an Google captcha See discription of this repository it solve hcaptcha

can u send a picture of the HCaptcha?

**Comment by HarshalCODE** [comment]
Code Is corrected
